name: Run Python Tests
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Test test_responses.py
        run: pytest tests/test_responses.py
      - name: Run Test test_metadata.py
        run: pytest tests/test_metadata.py
      - name: Run Test test_post_metadata_query.py
        run: pytest tests/test_post_metadata_query.py
      - name: Run Test test_signatures.py
        run: pytest tests/test_signatures.py
